{{- if and .Values.verdaccio.enabled .Values.artifusion.config.github.required_org .Values.secrets.github.token }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "artifusion.verdaccio.serviceName" . }}-secret
  labels:
    {{- include "artifusion.verdaccio.labels" . | nindent 4 }}
type: Opaque
stringData:
  npm-token: {{ .Values.secrets.github.token | quote }}
  .npmrc: |
    //npm.pkg.github.com/:_authToken=${NPM_TOKEN}
{{- end }}
