{{- if .Values.reposilite.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "artifusion.reposilite.serviceName" . }}
  labels:
    {{- include "artifusion.reposilite.labels" . | nindent 4 }}
data:
  configuration.cdn: |
    # Reposilite Configuration (No Authentication)
    # Auto-configured by Helm chart
    # Documentation: https://reposilite.com

    # ===== Web UI =====
    # Disable web interface (API-only mode)
    frontend false

    # ===== Hosted Repositories =====

    # Releases repository (immutable artifacts)
    repository releases {
      visibility public
      redeployment false
      preserveSnapshots false
      storageProvider fs releases
    }

    # Snapshots repository (mutable artifacts)
    repository snapshots {
      visibility public
      redeployment true
      preserveSnapshots true
      storageProvider fs snapshots
    }

    # ===== Mirror/Proxy Repositories (Cascade Priority Order) =====

    {{- if .Values.artifusion.config.github.required_org }}
    # 1. GitHub Packages (HIGHEST PRIORITY)
    # Requires authentication with GitHub PAT (read:packages scope)
    repository github-packages {
      visibility public
      redeployment false
      proxied {
        link https://maven.pkg.github.com
        store true
        storagePolicy PRIORITIZE_UPSTREAM_METADATA
        connectTimeout 3s
        readTimeout 15s
        allowedGroups *
        allowedExtensions jar war xml pom module asc md5 sha1 sha256 sha512
        # Authentication configured via header (GitHub uses Bearer token)
        authentication {
          type header
          headerName Authorization
          headerValue Bearer ${GITHUB_PACKAGES_TOKEN}
        }
      }
      storageProvider fs github-packages
    }
    {{- end }}

    # 2. Maven Central (PRIMARY PUBLIC REPOSITORY)
    repository maven-central {
      visibility public
      redeployment false
      proxied {
        link https://repo.maven.apache.org/maven2/
        store true
        storagePolicy PRIORITIZE_UPSTREAM_METADATA
        connectTimeout 3s
        readTimeout 15s
        allowedGroups *
        allowedExtensions jar war xml pom module asc md5 sha1 sha256 sha512
      }
      storageProvider fs maven-central
    }

    # 3. Google Maven (Android/Google libraries)
    repository google {
      visibility public
      redeployment false
      proxied {
        link https://maven.google.com/
        store true
        storagePolicy PRIORITIZE_UPSTREAM_METADATA
        connectTimeout 3s
        readTimeout 15s
        allowedGroups *
        allowedExtensions jar war aar xml pom module asc md5 sha1 sha256 sha512
      }
      storageProvider fs google
    }

    # 4. Spring Releases (Spring Framework libraries)
    repository spring-releases {
      visibility public
      redeployment false
      proxied {
        link https://repo.spring.io/release
        store true
        storagePolicy PRIORITIZE_UPSTREAM_METADATA
        connectTimeout 3s
        readTimeout 15s
        allowedGroups *
        allowedExtensions jar war xml pom module asc md5 sha1 sha256 sha512
      }
      storageProvider fs spring-releases
    }

    # 5. Gradle Plugins
    repository gradle-plugins {
      visibility public
      redeployment false
      proxied {
        link https://plugins.gradle.org/m2/
        store true
        storagePolicy PRIORITIZE_UPSTREAM_METADATA
        connectTimeout 3s
        readTimeout 15s
        allowedGroups *
        allowedExtensions jar war xml pom module asc md5 sha1 sha256 sha512
      }
      storageProvider fs gradle-plugins
    }

    # 6. JCenter (OPTIONAL - deprecated but still useful for legacy projects)
    # Note: JCenter is read-only as of May 2021
    repository jcenter {
      visibility public
      redeployment false
      proxied {
        link https://jcenter.bintray.com/
        store true
        storagePolicy PRIORITIZE_UPSTREAM_METADATA
        connectTimeout 3s
        readTimeout 15s
        allowedGroups *
        allowedExtensions jar war xml pom module asc md5 sha1 sha256 sha512
      }
      storageProvider fs jcenter
    }

    # ===== Access Tokens =====
    # No tokens configured - authentication handled by Artifusion
{{- end }}
