{{- if and .Values.reposilite.enabled .Values.artifusion.config.github.required_org .Values.secrets.github.token }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "artifusion.reposilite.serviceName" . }}-secret
  labels:
    {{- include "artifusion.reposilite.labels" . | nindent 4 }}
type: Opaque
stringData:
  github-token: {{ .Values.secrets.github.token | quote }}
{{- end }}
