# Development environment values
# Small storage sizes, no TLS, path-based routing

artifusion:
  replicaCount: 1

  config:
    logging:
      level: "debug"
      format: "console"
      force_color: true

  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi

  autoscaling:
    enabled: false

  podDisruptionBudget:
    enabled: false

  serviceMonitor:
    enabled: false

ociRegistry:
  storage:
    size: 1Gi

  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 200m
      memory: 512Mi

  podSecurityContext:
    runAsNonRoot: true
    runAsUser: 1000
    fsGroup: 1000

  securityContext:
    allowPrivilegeEscalation: false
    capabilities:
      drop: ["ALL"]

registry:
  storage:
    size: 1Gi

  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 200m
      memory: 256Mi

  podSecurityContext:
    runAsNonRoot: true
    runAsUser: 1000
    fsGroup: 1000

  securityContext:
    allowPrivilegeEscalation: false
    capabilities:
      drop: ["ALL"]

reposilite:
  storage:
    size: 1Gi

  resources:
    requests:
      cpu: 200m
      memory: 512Mi
    limits:
      cpu: 500m
      memory: 1Gi

  podSecurityContext:
    runAsNonRoot: true
    runAsUser: 1000
    fsGroup: 1000

  securityContext:
    allowPrivilegeEscalation: false
    capabilities:
      drop: ["ALL"]

verdaccio:
  storage:
    size: 1Gi

  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 200m
      memory: 256Mi

  podSecurityContext:
    runAsNonRoot: true
    runAsUser: 10001
    fsGroup: 65533

  securityContext:
    allowPrivilegeEscalation: false
    capabilities:
      drop: ["ALL"]

ingress:
  enabled: false  # Use port-forward for local dev

networkPolicy:
  enabled: false
