{{- if and .Values.ociRegistry.enabled (or .Values.secrets.github.token .Values.secrets.dockerhub.token) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "artifusion.ociRegistry.serviceName" . }}-creds
  labels:
    {{- include "artifusion.ociRegistry.labels" . | nindent 4 }}
type: Opaque
stringData:
  credentials: |-
    {{- $creds := list -}}
    {{- if .Values.secrets.github.token -}}
      {{- $creds = append $creds (printf "ghcr.io:%s:%s" .Values.secrets.github.username .Values.secrets.github.token) -}}
    {{- end -}}
    {{- if .Values.secrets.dockerhub.token -}}
      {{- $creds = append $creds (printf "registry-1.docker.io:%s:%s" .Values.secrets.dockerhub.username .Values.secrets.dockerhub.token) -}}
    {{- end -}}
    {{- join ";" $creds }}
{{- end }}
