{{- if and .Values.ociRegistry.enabled (or .Values.secrets.github.token .Values.secrets.dockerhub.token) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "artifusion.ociRegistry.serviceName" . }}-creds
  labels:
    {{- include "artifusion.ociRegistry.labels" . | nindent 4 }}
type: Opaque
stringData:
  credentials: |
    {{- $creds := dict }}
    {{- if .Values.secrets.github.token }}
    {{- $_ := set $creds "ghcr.io" (dict "username" .Values.secrets.github.username "password" .Values.secrets.github.token) }}
    {{- end }}
    {{- if .Values.secrets.dockerhub.token }}
    {{- $_ := set $creds "registry-1.docker.io" (dict "username" .Values.secrets.dockerhub.username "password" .Values.secrets.dockerhub.token) }}
    {{- end }}
    {{ toJson $creds }}
{{- end }}
